name: Smartling Uploader for Files Changed within 1 Day
on:
  push:
    branches:
      - master
  workflow_dispatch:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      db:
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: nexmo_developer_test
          POSTGRES_HOST_AUTH_METHOD: trust
        image: postgres:11
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Find yarn cache location
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - name: JS package cache
      uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Install packages
      run: |
        yarn install --pure-lockfile
    - name: Set up Ruby 2.5.8
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5.8
    - name: Ruby gem cache
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Install postgres headers
      run: sudo apt-get -yqq install libpq-dev
    - name: Bundle Install
      env:
        POSTGRES_USERNAME: postgres
        BUNDLE_RUBYGEMS__PKG__GITHUB__COM: "bencgreenberg:${{ secrets.GITHUB_TOKEN }}"
      run: |
        gem update --system 3.0.3 -N
        gem install --no-document bundler
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
  check-changes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - id: step1
      name: Check for File Changes
      run: |
        echo ::set-output name=file_changes::"arr=( $(git log --since=1.day --name-only --oneline --diff-filter=AMR --pretty=format: master _documentation/en _tutorials/en _use_cases/en | uniq | awk 'NF' | paste -d \",\" -s) )"
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  smartling-upload:
    if: steps.step1.outputs.file_changes != ''
    runs-on: ubuntu-latest
    needs: check-changes
    steps:
    - name: Run rake task
      env:
        POSTGRES_USERNAME: postgres
        OAS_PATH: "_open_api/api_specs/definitions"
        FORCE_COLOR: true
      run: |
        RAILS_ENV=test bundle exec nexmo-developer --docs=. --rake-smartling-upload 1 ${{steps.step1.outputs.file_changes}}
